[PHP]
; Dedicated ini for local dev server started via:
; php -c php.dev.ini -S 127.0.0.1:8000 -t public

extension_dir="C:\xampp\php\ext"

extension=pdo_pgsql
extension=pgsql
extension=pdo_mysql
extension=pdo_sqlite
extension=mysqli
extension=curl
extension=mbstring
extension=openssl
extension=fileinfo
extension=gd
extension=zip

display_errors=1
display_startup_errors=1
error_reporting=E_ALL

