<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260415185110 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ticket (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, action_type VARCHAR(100) NOT NULL, status VARCHAR(50) NOT NULL, progress INT NOT NULL, deadline_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_97A0ADA3B03A8386 ON ticket (created_by_id)');
        $this->addSql('CREATE TABLE ticket_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message TEXT NOT NULL, file_path VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ticket_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_98B80B3E700047D2 ON ticket_comment (ticket_id)');
        $this->addSql('CREATE INDEX IDX_98B80B3EA76ED395 ON ticket_comment (user_id)');
        $this->addSql('CREATE TABLE ticket_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(100) NOT NULL, details TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ticket_id INT NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2B762919700047D2 ON ticket_history (ticket_id)');
        $this->addSql('CREATE INDEX IDX_2B762919A76ED395 ON ticket_history (user_id)');
        $this->addSql('CREATE TABLE ticket_site (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ticket_id INT NOT NULL, site_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5B981CDC700047D2 ON ticket_site (ticket_id)');
        $this->addSql('CREATE INDEX IDX_5B981CDCF6BD1646 ON ticket_site (site_id)');
        $this->addSql('CREATE TABLE ticket_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, service_name VARCHAR(100) DEFAULT NULL, department_name VARCHAR(100) DEFAULT NULL, status VARCHAR(50) NOT NULL, comment TEXT DEFAULT NULL, proof_file VARCHAR(255) DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ticket_id INT NOT NULL, assigned_to_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_60A5CE1D700047D2 ON ticket_task (ticket_id)');
        $this->addSql('CREATE INDEX IDX_60A5CE1DF4BD7827 ON ticket_task (assigned_to_id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket_comment ADD CONSTRAINT FK_98B80B3E700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket_comment ADD CONSTRAINT FK_98B80B3EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket_history ADD CONSTRAINT FK_2B762919700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket_history ADD CONSTRAINT FK_2B762919A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket_site ADD CONSTRAINT FK_5B981CDC700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket_site ADD CONSTRAINT FK_5B981CDCF6BD1646 FOREIGN KEY (site_id) REFERENCES site (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket_task ADD CONSTRAINT FK_60A5CE1D700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket_task ADD CONSTRAINT FK_60A5CE1DF4BD7827 FOREIGN KEY (assigned_to_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA3B03A8386');
        $this->addSql('ALTER TABLE ticket_comment DROP CONSTRAINT FK_98B80B3E700047D2');
        $this->addSql('ALTER TABLE ticket_comment DROP CONSTRAINT FK_98B80B3EA76ED395');
        $this->addSql('ALTER TABLE ticket_history DROP CONSTRAINT FK_2B762919700047D2');
        $this->addSql('ALTER TABLE ticket_history DROP CONSTRAINT FK_2B762919A76ED395');
        $this->addSql('ALTER TABLE ticket_site DROP CONSTRAINT FK_5B981CDC700047D2');
        $this->addSql('ALTER TABLE ticket_site DROP CONSTRAINT FK_5B981CDCF6BD1646');
        $this->addSql('ALTER TABLE ticket_task DROP CONSTRAINT FK_60A5CE1D700047D2');
        $this->addSql('ALTER TABLE ticket_task DROP CONSTRAINT FK_60A5CE1DF4BD7827');
        $this->addSql('DROP TABLE ticket');
        $this->addSql('DROP TABLE ticket_comment');
        $this->addSql('DROP TABLE ticket_history');
        $this->addSql('DROP TABLE ticket_site');
        $this->addSql('DROP TABLE ticket_task');
    }
}
