<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260702110538 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE trafic_historique DROP created_at');
        $this->addSql('ALTER TABLE trafic_historique ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE trafic_historique ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX idx_trafic_historique_site RENAME TO idx_site');
        $this->addSql('ALTER INDEX idx_trafic_historique_date RENAME TO idx_date_heure');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE trafic_historique ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE trafic_historique ALTER id SET DEFAULT nextval(\'trafic_historique_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE trafic_historique ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX idx_site RENAME TO idx_trafic_historique_site');
        $this->addSql('ALTER INDEX idx_date_heure RENAME TO idx_trafic_historique_date');
    }
}
