<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260822224738 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE blocked_ip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ip_address VARCHAR(45) NOT NULL, reason VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, blocked_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3B25854B1DA661F8 ON blocked_ip (blocked_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_blocked_ip_address ON blocked_ip (ip_address)');
        $this->addSql('ALTER TABLE blocked_ip ADD CONSTRAINT FK_3B25854B1DA661F8 FOREIGN KEY (blocked_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD is_locked BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD locked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD lock_reason VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE blocked_ip DROP CONSTRAINT FK_3B25854B1DA661F8');
        $this->addSql('DROP TABLE blocked_ip');
        $this->addSql('ALTER TABLE "user" DROP is_locked');
        $this->addSql('ALTER TABLE "user" DROP locked_at');
        $this->addSql('ALTER TABLE "user" DROP lock_reason');
    }
}
