<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260513220522 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE service (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(255) DEFAULT NULL, color VARCHAR(20) DEFAULT NULL, default_deadline_days INT DEFAULT 5 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE processed_site ADD site_status VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE ticket_task ADD step_order INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE ticket_task ALTER requires_capture DROP DEFAULT');
        $this->addSql('ALTER TABLE ticket_task ALTER requires_capture SET NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE service');
        $this->addSql('ALTER TABLE processed_site DROP site_status');
        $this->addSql('ALTER TABLE ticket_task DROP step_order');
        $this->addSql('ALTER TABLE ticket_task ALTER requires_capture SET DEFAULT false');
        $this->addSql('ALTER TABLE ticket_task ALTER requires_capture DROP NOT NULL');
    }
}
