<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260417101044 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE processed_import (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, service_scope VARCHAR(50) NOT NULL, traffic_file_name VARCHAR(255) NOT NULL, ports_file_name VARCHAR(255) NOT NULL, liaison_file_name VARCHAR(255) NOT NULL, status VARCHAR(50) NOT NULL, total_sites INT NOT NULL, total_occurrences INT NOT NULL, imported_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, imported_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_857C930574953CEA ON processed_import (imported_by_id)');
        $this->addSql('CREATE TABLE processed_site (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, site_name VARCHAR(255) NOT NULL, paired_site_name VARCHAR(255) DEFAULT NULL, classification VARCHAR(100) NOT NULL, type_trans VARCHAR(100) DEFAULT NULL, max_trafic DOUBLE PRECISION DEFAULT NULL, date_max TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, seuil_critique DOUBLE PRECISION DEFAULT NULL, nombre_occurrences INT NOT NULL, total_measures INT NOT NULL, service_name VARCHAR(50) NOT NULL, is_critical BOOLEAN NOT NULL, processed_import_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_161C06B66355E390 ON processed_site (processed_import_id)');
        $this->addSql('ALTER TABLE processed_import ADD CONSTRAINT FK_857C930574953CEA FOREIGN KEY (imported_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE processed_site ADD CONSTRAINT FK_161C06B66355E390 FOREIGN KEY (processed_import_id) REFERENCES processed_import (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE processed_import DROP CONSTRAINT FK_857C930574953CEA');
        $this->addSql('ALTER TABLE processed_site DROP CONSTRAINT FK_161C06B66355E390');
        $this->addSql('DROP TABLE processed_import');
        $this->addSql('DROP TABLE processed_site');
    }
}
