<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260423090754 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE analyse_resultat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, site VARCHAR(100) NOT NULL, classification VARCHAR(50) NOT NULL, type_trans VARCHAR(50) DEFAULT NULL, max_trafic NUMERIC(15, 4) NOT NULL, seuil_critique NUMERIC(15, 4) NOT NULL, nombre_occurrences INT NOT NULL, total_measures INT NOT NULL, date_max TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, site_tdd VARCHAR(100) DEFAULT NULL, site_fdd VARCHAR(100) DEFAULT NULL, somme_fdd_tdd NUMERIC(15, 4) DEFAULT NULL, date_analyse TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, service_name VARCHAR(50) DEFAULT NULL, is_critical BOOLEAN NOT NULL, data_hash VARCHAR(64) DEFAULT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE analyse_resultat');
    }
}
