<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260428133341 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE workflow_ticket (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(100) NOT NULL, site_name VARCHAR(255) NOT NULL, service VARCHAR(50) NOT NULL, status VARCHAR(100) NOT NULL, current_step VARCHAR(100) NOT NULL, assigned_service VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, priority VARCHAR(50) NOT NULL, traffic_before DOUBLE PRECISION DEFAULT NULL, traffic_after DOUBLE PRECISION DEFAULT NULL, is_closed BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT DEFAULT NULL, assigned_to_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6A51760B03A8386 ON workflow_ticket (created_by_id)');
        $this->addSql('CREATE INDEX IDX_B6A51760F4BD7827 ON workflow_ticket (assigned_to_id)');
        $this->addSql('CREATE TABLE workflow_ticket_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(100) NOT NULL, from_step VARCHAR(100) DEFAULT NULL, to_step VARCHAR(100) DEFAULT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ticket_id INT NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F736EE24700047D2 ON workflow_ticket_history (ticket_id)');
        $this->addSql('CREATE INDEX IDX_F736EE24A76ED395 ON workflow_ticket_history (user_id)');
        $this->addSql('ALTER TABLE workflow_ticket ADD CONSTRAINT FK_B6A51760B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE workflow_ticket ADD CONSTRAINT FK_B6A51760F4BD7827 FOREIGN KEY (assigned_to_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE workflow_ticket_history ADD CONSTRAINT FK_F736EE24700047D2 FOREIGN KEY (ticket_id) REFERENCES workflow_ticket (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workflow_ticket_history ADD CONSTRAINT FK_F736EE24A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE workflow_ticket DROP CONSTRAINT FK_B6A51760B03A8386');
        $this->addSql('ALTER TABLE workflow_ticket DROP CONSTRAINT FK_B6A51760F4BD7827');
        $this->addSql('ALTER TABLE workflow_ticket_history DROP CONSTRAINT FK_F736EE24700047D2');
        $this->addSql('ALTER TABLE workflow_ticket_history DROP CONSTRAINT FK_F736EE24A76ED395');
        $this->addSql('DROP TABLE workflow_ticket');
        $this->addSql('DROP TABLE workflow_ticket_history');
    }
}
