<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20270704000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add controller access logs and seed the default controller account';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS user_access_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_logout_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USER_ACCESS_LOG_USER ON user_access_log (user_id)');
        $this->addSql('ALTER TABLE user_access_log ADD CONSTRAINT FK_USER_ACCESS_LOG_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $controllerPasswordHash = password_hash('controller1234', PASSWORD_DEFAULT);
        $controllerPasswordHashSql = str_replace("'", "''", $controllerPasswordHash);

        $this->addSql(sprintf(
            'INSERT INTO "user" (username, roles, password, service, department, email) VALUES (\'controller\', \'["ROLE_CONTROLLER"]\', \'%s\', NULL, NULL, \'controlleur@gmail.com\') ON CONFLICT (username) DO UPDATE SET roles = EXCLUDED.roles, password = EXCLUDED.password, service = EXCLUDED.service, department = EXCLUDED.department, email = EXCLUDED.email',
            $controllerPasswordHashSql
        ));
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE user_access_log DROP CONSTRAINT IF EXISTS FK_USER_ACCESS_LOG_USER');
        $this->addSql('DROP TABLE IF EXISTS user_access_log');
        $this->addSql('DELETE FROM "user" WHERE username = \'controller\'');
    }
}