<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260509093000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajout notifications, sous-workflows, recommandations IA, demandes MAJ site + priorité ticket';
    }

    public function up(Schema $schema): void
    {
        // Ticket priority
        $this->addSql("ALTER TABLE ticket ADD priority VARCHAR(20) NOT NULL DEFAULT 'medium'");

        // Notifications
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, ticket_id INT DEFAULT NULL, type VARCHAR(60) NOT NULL, message TEXT NOT NULL, is_read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CAA76ED395 ON notification (user_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CA700047D2 ON notification (ticket_id)');
        $this->addSql('CREATE INDEX idx_notification_user_is_read ON notification (user_id, is_read)');
        $this->addSql('CREATE INDEX idx_notification_created_at ON notification (created_at)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id) ON DELETE SET NULL NOT DEFERRABLE');

        // Sub-workflows
        $this->addSql('CREATE TABLE subworkflow (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, parent_ticket_id INT NOT NULL, child_ticket_id INT NOT NULL, created_by_id INT DEFAULT NULL, reason TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9D7E42E13B7B33E3 ON subworkflow (parent_ticket_id)');
        $this->addSql('CREATE INDEX IDX_9D7E42E14E6AF5F3 ON subworkflow (child_ticket_id)');
        $this->addSql('CREATE INDEX IDX_9D7E42E1B03A8386 ON subworkflow (created_by_id)');
        $this->addSql('CREATE INDEX idx_subworkflow_parent ON subworkflow (parent_ticket_id)');
        $this->addSql('CREATE INDEX idx_subworkflow_child ON subworkflow (child_ticket_id)');
        $this->addSql('ALTER TABLE subworkflow ADD CONSTRAINT FK_9D7E42E13B7B33E3 FOREIGN KEY (parent_ticket_id) REFERENCES ticket (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subworkflow ADD CONSTRAINT FK_9D7E42E14E6AF5F3 FOREIGN KEY (child_ticket_id) REFERENCES ticket (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subworkflow ADD CONSTRAINT FK_9D7E42E1B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');

        // AI recommendations (validated / modified / rejected)
        $this->addSql('CREATE TABLE ai_recommendation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, processed_site_id INT NOT NULL, decided_by_id INT DEFAULT NULL, status VARCHAR(30) NOT NULL, action_type VARCHAR(80) NOT NULL, assigned_service VARCHAR(50) NOT NULL, priority VARCHAR(20) NOT NULL, deadline_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, decision_comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C013B0CCB8D3E5F ON ai_recommendation (processed_site_id)');
        $this->addSql('CREATE INDEX IDX_4C013B0CA7B4A0A8 ON ai_recommendation (decided_by_id)');
        $this->addSql('CREATE INDEX idx_ai_rec_status ON ai_recommendation (status)');
        $this->addSql('CREATE INDEX idx_ai_rec_service ON ai_recommendation (assigned_service)');
        $this->addSql('ALTER TABLE ai_recommendation ADD CONSTRAINT FK_4C013B0CCB8D3E5F FOREIGN KEY (processed_site_id) REFERENCES processed_site (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ai_recommendation ADD CONSTRAINT FK_4C013B0CA7B4A0A8 FOREIGN KEY (decided_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');

        // Site update requests
        $this->addSql('CREATE TABLE site_update_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ticket_id INT NOT NULL, requested_by_id INT DEFAULT NULL, decided_by_id INT DEFAULT NULL, site_name VARCHAR(255) NOT NULL, new_capacity DOUBLE PRECISION DEFAULT NULL, new_support_type VARCHAR(100) DEFAULT NULL, upgrade_date DATE DEFAULT NULL, status VARCHAR(20) NOT NULL, decision_comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, decided_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3A6D145F700047D2 ON site_update_request (ticket_id)');
        $this->addSql('CREATE INDEX IDX_3A6D145F1D3EAB4E ON site_update_request (requested_by_id)');
        $this->addSql('CREATE INDEX IDX_3A6D145FA7B4A0A8 ON site_update_request (decided_by_id)');
        $this->addSql('CREATE INDEX idx_site_update_status ON site_update_request (status)');
        $this->addSql('ALTER TABLE site_update_request ADD CONSTRAINT FK_3A6D145F700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE site_update_request ADD CONSTRAINT FK_3A6D145F1D3EAB4E FOREIGN KEY (requested_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE site_update_request ADD CONSTRAINT FK_3A6D145FA7B4A0A8 FOREIGN KEY (decided_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CA700047D2');
        $this->addSql('DROP TABLE notification');

        $this->addSql('ALTER TABLE subworkflow DROP CONSTRAINT FK_9D7E42E13B7B33E3');
        $this->addSql('ALTER TABLE subworkflow DROP CONSTRAINT FK_9D7E42E14E6AF5F3');
        $this->addSql('ALTER TABLE subworkflow DROP CONSTRAINT FK_9D7E42E1B03A8386');
        $this->addSql('DROP TABLE subworkflow');

        $this->addSql('ALTER TABLE ai_recommendation DROP CONSTRAINT FK_4C013B0CCB8D3E5F');
        $this->addSql('ALTER TABLE ai_recommendation DROP CONSTRAINT FK_4C013B0CA7B4A0A8');
        $this->addSql('DROP TABLE ai_recommendation');

        $this->addSql('ALTER TABLE site_update_request DROP CONSTRAINT FK_3A6D145F700047D2');
        $this->addSql('ALTER TABLE site_update_request DROP CONSTRAINT FK_3A6D145F1D3EAB4E');
        $this->addSql('ALTER TABLE site_update_request DROP CONSTRAINT FK_3A6D145FA7B4A0A8');
        $this->addSql('DROP TABLE site_update_request');

        $this->addSql('ALTER TABLE ticket DROP COLUMN priority');
    }
}

