<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260625092131 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX idx_trafic_site_date');
        $this->addSql('ALTER TABLE trafic_historique ADD date_heure TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE trafic_historique ADD max_speed DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE trafic_historique DROP date_jour');
        $this->addSql('ALTER TABLE trafic_historique DROP max_trafic');
        $this->addSql('ALTER TABLE trafic_historique DROP capacite_mbps');
        $this->addSql('ALTER TABLE trafic_historique ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE trafic_historique ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE trafic_historique ADD date_jour DATE NOT NULL');
        $this->addSql('ALTER TABLE trafic_historique ADD max_trafic NUMERIC(15, 4) DEFAULT NULL');
        $this->addSql('ALTER TABLE trafic_historique ADD capacite_mbps NUMERIC(15, 4) DEFAULT NULL');
        $this->addSql('ALTER TABLE trafic_historique DROP date_heure');
        $this->addSql('ALTER TABLE trafic_historique DROP max_speed');
        $this->addSql('ALTER TABLE trafic_historique ALTER id SET DEFAULT nextval(\'trafic_historique_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE trafic_historique ALTER id DROP IDENTITY');
        $this->addSql('CREATE INDEX idx_trafic_site_date ON trafic_historique (site, date_jour)');
    }
}
