parameters:
    ticket_proofs_directory: '%kernel.project_dir%/public/uploads/ticket_proofs'
    cron_token: '%env(CRON_TOKEN)%'


services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            
    App\Chatbot\ChatbotService:
        arguments:
            $ollamaUrl: '%env(OLLAMA_URL)%'
            $ollamaModel: 'llama3.1:8b'
    
    App\Service\FastApiPortDetector:
        arguments:
            $apiBaseUrl: '%env(default::PYTHON_API_BASE_URL)%'
    App\EventListener\TicketDeadlineListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
    