parameters:
    ticket_proofs_directory: '%kernel.project_dir%/public/uploads/ticket_proofs'
    cron_token: '%env(CRON_TOKEN)%'


services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    
    App\Service\FastApiPortDetector: ~
    App\EventListener\TicketDeadlineListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
